services:
  mq:
    build:
      context: .
      dockerfile: Dockerfile
    image: mq
    environment:
      - SERVER_PORT=50051
      - ENVIRONMENT=production
      - WAL_DIR_PATH=/var/lib/mq
    volumes:
      - data:/var/lib/mq
    ports:
      - "50051:50051"
    container_name: mq

volumes:
  data:
    name: data