// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hitesh22rana/mq/pkg/utils (interfaces: Generator)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGenerator is a mock of Generator interface.
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorMockRecorder
}

// MockGeneratorMockRecorder is the mock recorder for MockGenerator.
type MockGeneratorMockRecorder struct {
	mock *MockGenerator
}

// NewMockGenerator creates a new mock instance.
func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &MockGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerator) EXPECT() *MockGeneratorMockRecorder {
	return m.recorder
}

// GetCurrentTimestamp mocks base method.
func (m *MockGenerator) GetCurrentTimestamp() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentTimestamp")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetCurrentTimestamp indicates an expected call of GetCurrentTimestamp.
func (mr *MockGeneratorMockRecorder) GetCurrentTimestamp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentTimestamp", reflect.TypeOf((*MockGenerator)(nil).GetCurrentTimestamp))
}

// GetUniqueMessageID mocks base method.
func (m *MockGenerator) GetUniqueMessageID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUniqueMessageID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUniqueMessageID indicates an expected call of GetUniqueMessageID.
func (mr *MockGeneratorMockRecorder) GetUniqueMessageID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUniqueMessageID", reflect.TypeOf((*MockGenerator)(nil).GetUniqueMessageID))
}

// GetUniqueSubscriberID mocks base method.
func (m *MockGenerator) GetUniqueSubscriberID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUniqueSubscriberID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUniqueSubscriberID indicates an expected call of GetUniqueSubscriberID.
func (mr *MockGeneratorMockRecorder) GetUniqueSubscriberID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUniqueSubscriberID", reflect.TypeOf((*MockGenerator)(nil).GetUniqueSubscriberID))
}
