name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: 
      - Test and PR Merge Check
    types:
      - completed

jobs:
  release:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: version
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (multi-arch) to ghcr.io
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t ghcr.io/${{ github.repository_owner }}/mq:${{ steps.version.outputs.TAG_NAME }} \
            -t ghcr.io/${{ github.repository_owner }}/mq:latest \
            --push .